### PR TITLE
fix: ValueError target column of train dataframe has NaN or Inf.

### PR DESCRIPTION
**Pull request by arima-tsukasa**
@AkiraUra 

The Inf check in the target column was deleted because it had already been performed elsewhere.

This PR is a part of the following PRs.

* [sapientml: fix/target_column_has_nan_or_inf](https://github.com/sapientml/sapientml/tree/fix/target_column_has_nan_or_inf)
* [loaddata: fix/target_column_has_nan_or_inf](https://github.com/sapientml/loaddata/tree/fix/target_column_has_nan_or_inf)

Please take a review on it.

### CODE REVIEW

**Review by AkiraUra — APPROVED** [review]
Than you for the PR. LGTM.

**Comment by kimusaku** [comment]
@arima-tsukasa it seems several commits in PR are not signed and thus the PR cannot be merged so far. Can you please sign each commit according to https://github.com/sapientml/sapientml/blob/main/CONTRIBUTING.md#i-did-not-sign-my-commit-now-what ? Thanks.

**Comment by arima-tsukasa** [comment]
> @arima-tsukasa it seems several commits in the PR are not signed and thus the PR cannot be merged so far. Can you please sign each commit according to https://github.com/sapientml/sapientml/blob/main/CONTRIBUTING.md#i-did-not-sign-my-commit-now-what ? Thanks.

The signature of merging the main modification was missing.
We have taken measures.

**Comment by arima-tsukasa** [comment]
@AkiraUra 

We have taken additional measures based on the following PR.
* https://github.com/sapientml/core/pull/55

The following fixes have been incorporated into the PR fixes.
* https://github.com/sapientml/loaddata/pull/12

**Review by AkiraUra — APPROVED** [review]
LGTM. Thank you!

**Pull request merged**
