### PR TITLE
feat: add all metrics at notebook.

### PR DESCRIPTION
**Pull request by arima-tsukasa**
@kimusaku 
@AkiraUra 

fixes : sapientml/sapientml#72 
Change final_script.py and final_script.py.ipynb to display the metrics that can be output.
It is as follows.
* classification:
  * F1
  * AUC
  * Accuracy
  * Gini
  * LogLoss
  * ROC_AUC
  * MCC
  * QWK
* regression:
  * R2
  * RMSLE
  * RMSE
  * MAE
  
However, Map@K is displayed only when specified.

### CODE REVIEW

**Review by AkiraUra — CHANGES_REQUESTED** [review]
Thank you for your PR.

`ROC AUC` and `AUC` are the same evaluation, so could you remove the duplication?

**Comment by arima-tsukasa** [comment]
https://github.com/sapientml/core/pull/54#pullrequestreview-1921759445

Duplicate evaluation removed.

**Comment by arima-tsukasa** [comment]
updated catboost from 1.2.2 to 1.2.3.
Corrected actions for changes.

https://github.com/catboost/catboost/releases/tag/v1.2.3
`[Breaking change]. Support a separate boolean target type, now predictions for models that have been trained with boolean targets will also be boolean instead of , strings as before. Such models will be incompatible with the previous versions of CatBoost appliers. If you want the old behavior convert your target to , strings before training. #1954ClassTrueFalseFalseTrue`

**Review by AkiraUra — APPROVED** [review]
Thank you. LGTM.

**Pull request merged**
